// Demo dataset for the Door2Door artifact surface (/dashboard/d2d).
//
// MOCK data for the demo. Types mirror the real `d2d_visits` / `d2d_workers`
// schema (see core/src/app/api/agent/d2d/log/route.ts) so a later swap to a live
// GET route is mechanical. ~186 visits: ~30 hand-curated (rich grievance notes)
// + the rest generated by a SEEDED PRNG so the set is deterministic (no SSR/
// hydration drift) yet realistic for KPIs, pagination, donut and top-issues.
// Field photos are real local thumbnails in /public/d2d-photos.

// ── value unions (match the DB / API) ───────────────────────────────────────
export type D2DOutcome = 'met' | 'not_home' | 'refused' | 'revisit';
export type D2DLean = 'supporter' | 'leaning' | 'undecided' | 'opposed';
export type GrievanceKey =
  | 'jobs' | 'water' | 'power' | 'roads' | 'drugs'
  | 'farm_debt' | 'health' | 'education' | 'other';
export type LoopStatus = 'raised' | 'routed' | 'resolved';

// ── shapes ───────────────────────────────────────────────────────────────────
export interface HouseholdMember {
  name: string;
  age: number;
  gender: 'M' | 'F';
  relation: string;
  voterIdMatched: boolean; // EPIC (voter-ID) matched on the doorstep
}

export interface D2DPhoto {
  id: string;
  url: string;   // real thumbnail in /public/d2d-photos
  label: string; // "House front", "Water supply", …
  takenAt: string;
}

export interface D2DSurvey {
  householdSize: number;
  members: HouseholdMember[];
  membersSpokenTo: number;
  flagHung: boolean;
  grievanceCategory?: GrievanceKey;
  grievanceNote?: string;
  lean?: D2DLean;
}

export interface VisitTimelineEntry {
  at: string;
  label: string;
  outcome: D2DOutcome;
}

export interface D2DVisit {
  id: string;
  householdHead: string;
  phone: string | null;
  workerId: string;
  workerName: string;
  workerPhone: string;
  constituency: string;
  district: string;
  acNo: number;
  boothNo: number;
  boothName: string;
  addressNote: string;
  latitude: number | null;
  longitude: number | null;
  outcome: D2DOutcome;
  notes?: string;
  survey: D2DSurvey | null;
  surveyVersion: string | null;
  photos: D2DPhoto[];
  loopStatus?: LoopStatus;
  visitedAt: string;
  timeline: VisitTimelineEntry[];
}

export interface D2DWorker {
  id: string;
  name: string;
  phone: string;
  constituency: string;
  district: string;
  boothAssignments: string[];
  verificationCode: string;
  status: 'active' | 'inactive';
}

export interface BoothCampaign {
  id: string;
  name: string;
  description: string;
  constituency: string;
  district: string;
  booths: number[];
  startDate: string;
  endDate: string;
  targetDoors: number;
  doorsDone: number;
  workerIds: string[];
  status: 'active' | 'completed';
}

// ── display config maps (colors align with LeadsTable POP_* maps) ────────────
// Note: outcome 'revisit' is DISPLAYED as "Follow-up" (schema value unchanged).
export const D2D_OUTCOME: Record<D2DOutcome, { label: string; color: string }> = {
  met:      { label: 'Met',       color: '#22C55E' },
  not_home: { label: 'Not Home',  color: '#8A8A8A' },
  refused:  { label: 'Refused',   color: '#EF4444' },
  revisit:  { label: 'Follow-up', color: '#F59E0B' },
};

export const D2D_LEAN: Record<D2DLean, { label: string; color: string }> = {
  supporter: { label: 'Supporter', color: '#22C55E' },
  leaning:   { label: 'Leaning',   color: '#84CC16' },
  undecided: { label: 'Undecided', color: '#F59E0B' },
  opposed:   { label: 'Opposed',   color: '#EF4444' },
};

export const D2D_GRIEVANCE: Record<GrievanceKey, { label: string; color: string }> = {
  jobs:      { label: 'Jobs',      color: '#3B82F6' },
  water:     { label: 'Water',     color: '#06B6D4' },
  power:     { label: 'Power',     color: '#F59E0B' },
  roads:     { label: 'Roads',     color: '#A78BFA' },
  drugs:     { label: 'Drugs',     color: '#EC4899' },
  farm_debt: { label: 'Farm Debt', color: '#F97316' },
  health:    { label: 'Health',    color: '#EF4444' },
  education: { label: 'Education', color: '#8B5CF6' },
  other:     { label: 'Other',     color: '#6B7280' },
};

export const D2D_LOOP: Record<LoopStatus, { label: string; color: string }> = {
  raised:   { label: 'Raised',   color: '#F59E0B' },
  routed:   { label: 'Routed',   color: '#3B82F6' },
  resolved: { label: 'Resolved', color: '#22C55E' },
};

// ── time helpers (generated relative to now) ─────────────────────────────────
const NOW = Date.now();
export function hoursAgo(h: number): string {
  return new Date(NOW - h * 3_600_000).toISOString();
}
export function daysAgo(d: number): string {
  return hoursAgo(d * 24);
}
export function timeAgo(iso: string | null | undefined): string {
  if (!iso) return '-';
  const diffMs = NOW - new Date(iso).getTime();
  const mins = Math.floor(diffMs / 60000);
  if (mins < 1) return 'now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days}d ago`;
  return `${Math.floor(days / 30)}mo ago`;
}
export function districtColor(d: string): string {
  let h = 0;
  for (let i = 0; i < d.length; i++) h = (h * 31 + d.charCodeAt(i)) % 360;
  return `hsl(${h}, 60%, 52%)`;
}

// ── real field photos ────────────────────────────────────────────────────────
const PB = '/d2d-photos/';
const HOUSE_PICS = ['house-a', 'house-b', 'house-c', 'house-d'];
const GRV_PICS: Record<GrievanceKey, string[]> = {
  water: ['water-a', 'water-b'],
  power: ['power-a'],
  roads: ['road-a'],
  farm_debt: ['farm-a', 'farm-b'],
  education: ['school-a'],
  drugs: ['lane-a'],
  health: ['drain-a'],
  jobs: ['lane-a'],
  other: ['drain-a'],
};
function picLabel(slug: string): string {
  if (slug.startsWith('house')) return 'House front';
  if (slug.startsWith('water')) return 'Water supply';
  if (slug.startsWith('power')) return 'Power lines';
  if (slug.startsWith('road')) return 'Road condition';
  if (slug.startsWith('drain')) return 'Drainage';
  if (slug.startsWith('school')) return 'School';
  if (slug.startsWith('farm')) return 'Farm land';
  if (slug.startsWith('lane')) return 'Street';
  return 'Photo';
}
function photo(slug: string, id: string, at: string): D2DPhoto {
  return { id, url: `${PB}${slug}.jpg`, label: picLabel(slug), takenAt: at };
}

// ── booths (real Punjab ACs, denormalized like d2d_visits text columns) ──────
interface BoothDef { no: number; name: string; constituency: string; district: string; acNo: number; lat: number; lng: number; }
const BOOTHS: Record<number, BoothDef> = {
  42:  { no: 42,  name: 'Govt Primary School, Ranjit Nagar',    constituency: 'Amritsar East',  district: 'Amritsar', acNo: 18, lat: 31.6340, lng: 74.8723 },
  51:  { no: 51,  name: 'Govt Girls School, Gopal Nagar',       constituency: 'Amritsar East',  district: 'Amritsar', acNo: 18, lat: 31.6412, lng: 74.8801 },
  47:  { no: 47,  name: 'Community Hall, Maqbool Road',         constituency: 'Amritsar East',  district: 'Amritsar', acNo: 18, lat: 31.6288, lng: 74.8659 },
  118: { no: 118, name: 'Govt Sr Sec School, Basti Bawa Khel',  constituency: 'Jalandhar West', district: 'Jalandhar', acNo: 34, lat: 31.3120, lng: 75.5590 },
  122: { no: 122, name: 'Municipal Primary School, Rama Mandi', constituency: 'Jalandhar West', district: 'Jalandhar', acNo: 34, lat: 31.2977, lng: 75.5701 },
  88:  { no: 88,  name: 'Govt School, Dugri Phase 1',           constituency: 'Ludhiana South', district: 'Ludhiana', acNo: 63, lat: 30.8650, lng: 75.8420 },
  91:  { no: 91,  name: 'Panchayat Ghar, Model Town',           constituency: 'Ludhiana South', district: 'Ludhiana', acNo: 63, lat: 30.8830, lng: 75.8510 },
  12:  { no: 12,  name: 'Govt Primary School, Bhadson Road',    constituency: 'Patiala Rural',  district: 'Patiala', acNo: 106, lat: 30.3610, lng: 76.3790 },
  19:  { no: 19,  name: 'Village Panchayat Ghar, Kheri Gujran', constituency: 'Patiala Rural',  district: 'Patiala', acNo: 106, lat: 30.3902, lng: 76.4120 },
  63:  { no: 63,  name: 'Govt Sr Sec School, Paras Ram Nagar',  constituency: 'Bathinda Urban', district: 'Bathinda', acNo: 96, lat: 30.2100, lng: 74.9455 },
  67:  { no: 67,  name: 'Community Centre, Amrik Singh Road',   constituency: 'Bathinda Urban', district: 'Bathinda', acNo: 96, lat: 30.2077, lng: 74.9510 },
};
// Expand the booth universe to campaign scale (~48 booths) so the Booth
// Campaigns view (priority queue, breakdown donut, headline KPIs) reads like a
// real week of ground work, not a handful of curated rows. Deterministic via a
// local seeded RNG (the module `rnd` isn't defined yet at this point).
;(function expandBooths() {
  const AREAS = ['Ranjit Nagar', 'Gopal Nagar', 'Maqbool Road', 'Basti Bawa Khel', 'Rama Mandi', 'Dugri', 'Model Town', 'Bhadson Road', 'Kheri Gujran', 'Paras Ram Nagar', 'Amrik Singh Road', 'Sunder Nagar', 'Guru Nanak Pura', 'Ram Tirath Road', 'Chheharta', 'Focal Point', 'Kot Khalsa', 'Gandhi Camp', 'Preet Nagar', 'Shastri Nagar', 'Ekta Vihar', 'Sultanwind', 'Verka', 'Majitha Road', 'Green Avenue', 'Nai Abadi', 'Bank Colony', 'Partap Avenue', 'Krishna Nagar', 'Haibowal', 'Jamalpur', 'Baddowal', 'Threeke', 'Sahnewal', 'Doraha', 'Rajpura', 'Nabha Road', 'Cantt Area']
  const TEMPLATES = ['Govt Primary School', 'Govt Girls School', 'Govt Sr Sec School', 'Community Hall', 'Panchayat Ghar', 'Municipal School', 'Anganwadi Centre', 'Village Dharamshala']
  const SEATS = [
    { constituency: 'Amritsar East', district: 'Amritsar', acNo: 18, lat: 31.63, lng: 74.87 },
    { constituency: 'Jalandhar West', district: 'Jalandhar', acNo: 34, lat: 31.31, lng: 75.56 },
    { constituency: 'Ludhiana South', district: 'Ludhiana', acNo: 63, lat: 30.87, lng: 75.85 },
    { constituency: 'Patiala Rural', district: 'Patiala', acNo: 106, lat: 30.37, lng: 76.39 },
    { constituency: 'Bathinda Urban', district: 'Bathinda', acNo: 96, lat: 30.21, lng: 74.95 },
  ]
  let s = 0x9e3779b9 | 0
  const r = () => { s = (s + 0x6D2B79F5) | 0; let t = Math.imul(s ^ (s >>> 15), 1 | s); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296 }
  const p = <T,>(a: T[]): T => a[Math.floor(r() * a.length)]
  let no = 130
  for (let i = 0; i < 37; i++) {
    while (BOOTHS[no]) no++
    const seat = p(SEATS)
    BOOTHS[no] = { no, name: `${p(TEMPLATES)}, ${p(AREAS)}`, constituency: seat.constituency, district: seat.district, acNo: seat.acNo, lat: seat.lat + (r() - 0.5) * 0.05, lng: seat.lng + (r() - 0.5) * 0.05 }
    no++
  }
})();
const BOOTH_NOS = Object.keys(BOOTHS).map(Number);

// ── workers ──────────────────────────────────────────────────────────────────
export const WORKERS: D2DWorker[] = [
  { id: 'w1', name: 'Gurpreet Singh',  phone: '+919876500011', constituency: 'Amritsar East',  district: 'Amritsar',  boothAssignments: ['42', '51'],  verificationCode: 'POP-4K2Q7A', status: 'active' },
  { id: 'w2', name: 'Harjinder Kaur',  phone: '+919876500022', constituency: 'Amritsar East',  district: 'Amritsar',  boothAssignments: ['47'],        verificationCode: 'POP-9XR3M1', status: 'active' },
  { id: 'w3', name: 'Baldev Sandhu',   phone: '+919876500033', constituency: 'Jalandhar West', district: 'Jalandhar', boothAssignments: ['118', '122'], verificationCode: 'POP-2H8W5C', status: 'active' },
  { id: 'w4', name: 'Simran Dhillon',  phone: '+919876500044', constituency: 'Ludhiana South', district: 'Ludhiana',  boothAssignments: ['88', '91'],  verificationCode: 'POP-7T1N6E', status: 'active' },
  { id: 'w5', name: 'Jaspal Brar',     phone: '+919876500055', constituency: 'Patiala Rural',  district: 'Patiala',   boothAssignments: ['12', '19'],  verificationCode: 'POP-5B9D2F', status: 'active' },
  { id: 'w6', name: 'Navdeep Gill',    phone: '+919876500066', constituency: 'Bathinda Urban', district: 'Bathinda',  boothAssignments: ['63', '67'],  verificationCode: 'POP-3M6Y8K', status: 'active' },
  { id: 'w7', name: 'Amrit Sekhon',    phone: '+919876500077', constituency: 'Jalandhar West', district: 'Jalandhar', boothAssignments: ['118'],       verificationCode: 'POP-8P4L1Z', status: 'active' },
];
const workerById = Object.fromEntries(WORKERS.map((w) => [w.id, w]));
const workersForBooth = (no: number) => WORKERS.filter((w) => w.boothAssignments.includes(String(no)));

// ── curated visit factory ────────────────────────────────────────────────────
let _seq = 0;
interface VisitSpec {
  head: string; phone?: string | null; workerId: string; boothNo: number; addr: string;
  outcome: D2DOutcome; hoursAgo: number; members?: HouseholdMember[]; spokenTo?: number;
  flagHung?: boolean; grievance?: GrievanceKey; grievanceNote?: string; lean?: D2DLean;
  loop?: LoopStatus; notes?: string; extraHousePic?: boolean;
  priorKnock?: { outcome: D2DOutcome; hoursAgo: number; label?: string };
}
function m(name: string, age: number, gender: 'M' | 'F', relation: string, voterIdMatched = true): HouseholdMember {
  return { name, age, gender, relation, voterIdMatched };
}
function buildPhotos(spec: { grievance?: GrievanceKey; extraHousePic?: boolean }, seqIx: number, at: string): D2DPhoto[] {
  const out: D2DPhoto[] = [];
  out.push(photo(HOUSE_PICS[seqIx % HOUSE_PICS.length], `p${seqIx}-h`, at));
  if (spec.grievance) {
    const pool = GRV_PICS[spec.grievance];
    out.push(photo(pool[seqIx % pool.length], `p${seqIx}-g`, at));
  }
  if (spec.extraHousePic) out.push(photo(HOUSE_PICS[(seqIx + 2) % HOUSE_PICS.length], `p${seqIx}-h2`, at));
  return out;
}
function mkVisit(s: VisitSpec): D2DVisit {
  _seq += 1;
  const b = BOOTHS[s.boothNo];
  const w = workerById[s.workerId];
  const visitedAt = hoursAgo(s.hoursAgo);
  const isMet = s.outcome === 'met';
  const survey: D2DSurvey | null = isMet && s.members
    ? {
        householdSize: s.members.length,
        members: s.members,
        membersSpokenTo: s.spokenTo ?? Math.min(s.members.length, 2),
        flagHung: !!s.flagHung,
        grievanceCategory: s.grievance,
        grievanceNote: s.grievanceNote,
        lean: s.lean,
      }
    : null;
  const photos = isMet ? buildPhotos(s, _seq, visitedAt) : [];
  const timeline: VisitTimelineEntry[] = [];
  if (s.priorKnock) {
    timeline.push({
      at: hoursAgo(s.priorKnock.hoursAgo),
      label: s.priorKnock.label || (s.priorKnock.outcome === 'not_home' ? 'First knock - not home' : `First knock - ${D2D_OUTCOME[s.priorKnock.outcome].label.toLowerCase()}`),
      outcome: s.priorKnock.outcome,
    });
  }
  timeline.push({
    at: visitedAt,
    label: s.outcome === 'met' ? `${s.priorKnock ? 'Revisit - met' : 'Met'}${s.flagHung ? ', flag hung' : ''}` : D2D_OUTCOME[s.outcome].label,
    outcome: s.outcome,
  });
  return {
    id: `v${_seq}`,
    householdHead: s.head,
    phone: s.phone === undefined ? (isMet ? `+9198${String(76000000 + _seq * 7).slice(0, 8)}` : null) : s.phone,
    workerId: s.workerId, workerName: w.name, workerPhone: w.phone,
    constituency: b.constituency, district: b.district, acNo: b.acNo,
    boothNo: b.no, boothName: b.name, addressNote: s.addr,
    latitude: b.lat, longitude: b.lng,
    outcome: s.outcome, notes: s.notes,
    survey, surveyVersion: isMet ? 'v1' : null, photos,
    loopStatus: s.grievance ? s.loop || 'raised' : undefined,
    visitedAt, timeline,
  };
}

const CURATED: D2DVisit[] = [
  mkVisit({ head: 'Sukhdev Singh', workerId: 'w3', boothNo: 118, addr: 'H.No B42-118, Basti Bawa Khel', outcome: 'met', hoursAgo: 0.2, spokenTo: 3,
    members: [m('Sukhdev Singh', 50, 'M', 'Head'), m('Manpreet Kaur', 46, 'F', 'Spouse'), m('Jashan Singh', 21, 'M', 'Son', true), m('Ekamjot Kaur', 16, 'F', 'Daughter', false)],
    flagHung: true, grievance: 'farm_debt', grievanceNote: 'Crop loan pending, mandi payment delayed', lean: 'leaning', loop: 'routed', extraHousePic: true }),
  mkVisit({ head: 'Baldev Singh', workerId: 'w1', boothNo: 42, addr: 'H.No 12, Street 2', outcome: 'met', hoursAgo: 0.45, spokenTo: 3,
    members: [m('Baldev Singh', 52, 'M', 'Head'), m('Sukhwinder Kaur', 48, 'F', 'Spouse'), m('Gurleen Kaur', 22, 'F', 'Daughter', false), m('Arshdeep Singh', 19, 'M', 'Son', false)],
    flagHung: true, grievance: 'water', grievanceNote: 'Tubewell water muddy for 3 weeks, no supply after 9am', lean: 'leaning', loop: 'routed', extraHousePic: true }),
  mkVisit({ head: 'Manjit Singh', workerId: 'w1', boothNo: 42, addr: 'H.No 78, Street 5', outcome: 'met', hoursAgo: 0.9, spokenTo: 5,
    members: [m('Manjit Singh', 41, 'M', 'Head'), m('Rajwant Kaur', 38, 'F', 'Spouse'), m('Harpreet Singh', 20, 'M', 'Son', true), m('Simar Kaur', 18, 'F', 'Daughter', true), m('Gurcharan Singh', 68, 'M', 'Father', true)],
    flagHung: false, grievance: 'jobs', grievanceNote: 'Son graduate, no work since 2 years', lean: 'supporter' }),
  mkVisit({ head: 'Kulwant Singh', workerId: 'w1', boothNo: 42, addr: 'H.No 210, Gali No 7', outcome: 'not_home', hoursAgo: 1 }),
  mkVisit({ head: 'Paramjit Kaur', workerId: 'w1', boothNo: 42, addr: 'H.No 36, Street 3', outcome: 'met', hoursAgo: 1.4, spokenTo: 2,
    members: [m('Paramjit Kaur', 60, 'F', 'Head'), m('Harpreet Singh', 34, 'M', 'Son'), m('Simarjeet Kaur', 30, 'F', 'Daughter-in-law'), m('Ekam Singh', 6, 'M', 'Grandson', false)],
    flagHung: false, grievance: 'health', grievanceNote: 'PHC too far, no ambulance in ward', lean: 'undecided', loop: 'raised' }),
  mkVisit({ head: 'Gurdeep Singh', workerId: 'w1', boothNo: 47, addr: 'H.No 91, Gali No 2', outcome: 'refused', hoursAgo: 2, notes: 'Declined survey, busy' }),
  mkVisit({ head: 'Rakesh Sharma', workerId: 'w4', boothNo: 88, addr: 'H.No 65, Street 4', outcome: 'met', hoursAgo: 2.5, spokenTo: 3,
    members: [m('Rakesh Sharma', 43, 'M', 'Head'), m('Neha Sharma', 39, 'F', 'Spouse'), m('Aarav Sharma', 15, 'M', 'Son', false)],
    flagHung: true, grievance: 'power', grievanceNote: 'Voltage fluctuation damaging appliances', lean: 'supporter', loop: 'routed' }),
  mkVisit({ head: 'Tejinder Singh', workerId: 'w2', boothNo: 47, addr: 'H.No 18, Street 1', outcome: 'revisit', hoursAgo: 3, spokenTo: 1,
    priorKnock: { outcome: 'not_home', hoursAgo: 52 }, grievance: 'drugs', grievanceNote: 'Peddling near school, youth affected', lean: 'supporter', loop: 'raised',
    members: [m('Tejinder Singh', 39, 'M', 'Head'), m('Harmanpreet Kaur', 36, 'F', 'Spouse')] }),
  mkVisit({ head: 'Mohan Lal', workerId: 'w2', boothNo: 47, addr: 'H.No 61, Madbool Road', outcome: 'not_home', hoursAgo: 4 }),
  mkVisit({ head: 'Jaswinder Kaur', workerId: 'w3', boothNo: 122, addr: 'H.No 8, Gali No 6', outcome: 'met', hoursAgo: 4.3, spokenTo: 4,
    members: [m('Jaswinder Kaur', 49, 'F', 'Head'), m('Paramjeet Singh', 52, 'M', 'Spouse'), m('Lovepreet Singh', 23, 'M', 'Son', true), m('Simran Kaur', 19, 'F', 'Daughter', true)],
    flagHung: true, grievance: 'roads', grievanceNote: 'Street unpaved, waterlogging in monsoon', lean: 'leaning', loop: 'routed', extraHousePic: true }),
  mkVisit({ head: 'Satnam Singh', workerId: 'w1', boothNo: 51, addr: 'H.No 12, Gopal Nagar', outcome: 'met', hoursAgo: 20, spokenTo: 2,
    members: [m('Satnam Singh', 45, 'M', 'Head'), m('Balwinder Kaur', 43, 'F', 'Spouse'), m('Jasmeet Singh', 18, 'M', 'Son', true)],
    flagHung: true, grievance: 'power', grievanceNote: '6+ hour cuts daily, transformer overloaded', lean: 'supporter', loop: 'routed' }),
  mkVisit({ head: 'Amarjit Kaur', workerId: 'w1', boothNo: 51, addr: 'H.No 88, Gopal Nagar', outcome: 'revisit', hoursAgo: 22, priorKnock: { outcome: 'not_home', hoursAgo: 70 }, notes: 'Asked to come back evening' }),
  mkVisit({ head: 'Iqbal Singh', workerId: 'w7', boothNo: 118, addr: 'H.No B42-133, Basti Bawa Khel', outcome: 'met', hoursAgo: 26, spokenTo: 2,
    members: [m('Iqbal Singh', 44, 'M', 'Head'), m('Sarabjit Kaur', 40, 'F', 'Spouse'), m('Harnoor Singh', 12, 'M', 'Son', false)],
    flagHung: true, lean: 'undecided' }),
  mkVisit({ head: 'Karnail Singh', workerId: 'w2', boothNo: 47, addr: 'H.No 104, Maqbool Road', outcome: 'met', hoursAgo: 28, spokenTo: 2,
    members: [m('Karnail Singh', 63, 'M', 'Head'), m('Jaspreet Kaur', 58, 'F', 'Spouse')],
    flagHung: false, grievance: 'roads', grievanceNote: 'Approach road broken, autos refuse to come', lean: 'undecided', loop: 'raised' }),
  mkVisit({ head: 'Gurmail Singh', workerId: 'w3', boothNo: 122, addr: 'H.No 22, Rama Mandi', outcome: 'met', hoursAgo: 30, spokenTo: 4,
    members: [m('Gurmail Singh', 49, 'M', 'Head'), m('Paramjeet Kaur', 45, 'F', 'Spouse'), m('Lovepreet Singh', 23, 'M', 'Son', true), m('Simran Kaur', 19, 'F', 'Daughter', true)],
    flagHung: true, grievance: 'jobs', grievanceNote: 'Both children unemployed graduates', lean: 'supporter', loop: 'routed', extraHousePic: true }),
  mkVisit({ head: 'Sohan Singh', workerId: 'w5', boothNo: 12, addr: 'Ward 3, Bhadson Road', outcome: 'met', hoursAgo: 34, spokenTo: 3,
    members: [m('Sohan Singh', 54, 'M', 'Head'), m('Gurmeet Kaur', 50, 'F', 'Spouse'), m('Karan Singh', 27, 'M', 'Son', true), m('Jashanpreet Kaur', 23, 'F', 'Daughter-in-law', true)],
    flagHung: true, grievance: 'farm_debt', grievanceNote: 'Diesel + fertiliser cost too high', lean: 'leaning', loop: 'routed' }),
  mkVisit({ head: 'Ashok Garg', workerId: 'w6', boothNo: 63, addr: 'H.No 14, Paras Ram Nagar', outcome: 'met', hoursAgo: 38, spokenTo: 3,
    members: [m('Ashok Garg', 50, 'M', 'Head'), m('Sunita Garg', 46, 'F', 'Spouse'), m('Nikita Garg', 20, 'F', 'Daughter', true), m('Dhruv Garg', 16, 'M', 'Son', false)],
    flagHung: true, grievance: 'health', grievanceNote: 'Civil hospital understaffed', lean: 'supporter', loop: 'routed' }),
  mkVisit({ head: 'Resham Singh', workerId: 'w5', boothNo: 19, addr: 'Kheri Gujran, near Gurudwara', outcome: 'met', hoursAgo: 44, spokenTo: 2,
    members: [m('Resham Singh', 48, 'M', 'Head'), m('Baljeet Kaur', 45, 'F', 'Spouse'), m('Sahil Singh', 22, 'M', 'Son', true)],
    flagHung: false, grievance: 'water', grievanceNote: 'Canal water share reduced this season', lean: 'undecided', loop: 'raised' }),
  mkVisit({ head: 'Sukhpal Singh', workerId: 'w6', boothNo: 67, addr: 'H.No 3, Amrik Singh Road', outcome: 'met', hoursAgo: 50, spokenTo: 2,
    members: [m('Sukhpal Singh', 42, 'M', 'Head'), m('Rajwinder Kaur', 39, 'F', 'Spouse'), m('Gurfateh Singh', 9, 'M', 'Son', false)],
    flagHung: true, grievance: 'education', grievanceNote: 'No govt college within 15km', lean: 'supporter', loop: 'raised' }),
  mkVisit({ head: 'Darshan Lal', workerId: 'w3', boothNo: 118, addr: 'H.No B42-090, Basti Bawa Khel', outcome: 'met', hoursAgo: 54, spokenTo: 3,
    members: [m('Darshan Lal', 58, 'M', 'Head'), m('Kamlesh Rani', 54, 'F', 'Spouse'), m('Rohit Kumar', 28, 'M', 'Son', true)],
    flagHung: false, grievance: 'education', grievanceNote: 'Govt school short of teachers', lean: 'supporter', loop: 'resolved' }),
];

// ── seeded generator (fills out to ~186) ─────────────────────────────────────
function mulberry32(seed: number) {
  return function () {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(0x50504f50); // fixed seed → deterministic
const pick = <T,>(arr: T[]): T => arr[Math.floor(rnd() * arr.length)];
const weighted = <T,>(items: [T, number][]): T => {
  const total = items.reduce((s, [, w]) => s + w, 0);
  let r = rnd() * total;
  for (const [v, w] of items) { if ((r -= w) <= 0) return v; }
  return items[items.length - 1][0];
};

const MALE = ['Harjit', 'Gurmeet', 'Balwinder', 'Jarnail', 'Ranjit', 'Davinder', 'Surinder', 'Tejinder', 'Kuldeep', 'Amarjit', 'Hardeep', 'Sukhwinder', 'Jagtar', 'Balkar', 'Nirmal', 'Pargat', 'Malkit', 'Charanjit', 'Rachhpal', 'Beant', 'Avtar', 'Harbans', 'Gurmail', 'Sohan', 'Mohinder'];
const FEMALE = ['Harpreet', 'Rajwinder', 'Baljit', 'Kuldeep', 'Manjit', 'Surjit', 'Amandeep', 'Gurmeet', 'Paramjit', 'Sarbjit', 'Jasbir', 'Narinder', 'Charanjit', 'Balwinder', 'Harjinder', 'Ravinder', 'Sukhjit', 'Daljit'];
const SURNAME = ['Singh', 'Singh', 'Singh', 'Kaur', 'Kaur', 'Sharma', 'Kumar', 'Garg', 'Lal', 'Rani'];
const RELATION_M = ['Son', 'Father', 'Brother', 'Uncle'];
const RELATION_F = ['Daughter', 'Mother', 'Spouse', 'Daughter-in-law'];

function genMembers(): HouseholdMember[] {
  const size = weighted<number>([[2, 3], [3, 4], [4, 5], [5, 3], [6, 2]]);
  const headMale = rnd() > 0.25;
  const headSur = pick(SURNAME.filter((s) => s !== 'Kaur' && s !== 'Rani')) || 'Singh';
  const members: HouseholdMember[] = [];
  const head = headMale ? `${pick(MALE)} ${headSur === 'Kaur' ? 'Singh' : headSur}` : `${pick(FEMALE)} Kaur`;
  members.push(m(head, 38 + Math.floor(rnd() * 30), headMale ? 'M' : 'F', 'Head', true));
  if (size > 1) members.push(m(`${pick(FEMALE)} Kaur`, 34 + Math.floor(rnd() * 26), 'F', 'Spouse', rnd() > 0.15));
  for (let i = members.length; i < size; i++) {
    const male = rnd() > 0.5;
    const age = 8 + Math.floor(rnd() * 45);
    members.push(m(
      male ? `${pick(MALE)} Singh` : `${pick(FEMALE)} Kaur`,
      age, male ? 'M' : 'F',
      male ? pick(RELATION_M) : pick(RELATION_F),
      age >= 18 ? rnd() > 0.35 : false,
    ));
  }
  return members;
}

function generated(count: number): D2DVisit[] {
  const out: D2DVisit[] = [];
  for (let i = 0; i < count; i++) {
    const boothNo = pick(BOOTH_NOS);
    const w = pick(workersForBooth(boothNo).length ? workersForBooth(boothNo) : WORKERS);
    const outcome = weighted<D2DOutcome>([['met', 0.68], ['not_home', 0.15], ['revisit', 0.11], ['refused', 0.06]]);
    const hrs = 4 + rnd() * 164; // spread over ~7 days, after the curated recent ones
    if (outcome !== 'met') {
      const spec: VisitSpec = {
        head: rnd() > 0.3 ? `${pick(MALE)} Singh` : `${pick(FEMALE)} Kaur`,
        workerId: w.id, boothNo, addr: `H.No ${20 + Math.floor(rnd() * 260)}, ${pick(['Gali No 3', 'Gali No 5', 'Gali No 8', 'Main Bazaar', 'Ward 4', 'Ward 7', 'Model Colony'])}`,
        outcome, hoursAgo: hrs,
        notes: outcome === 'refused' ? pick(['Not interested', 'Busy, declined', 'Asked not to return']) : undefined,
        priorKnock: outcome === 'revisit' ? { outcome: 'not_home', hoursAgo: hrs + 48 + rnd() * 72 } : undefined,
      };
      out.push(mkVisit(spec));
      continue;
    }
    const members = genMembers();
    const lean = weighted<D2DLean>([['supporter', 0.40], ['leaning', 0.32], ['undecided', 0.18], ['opposed', 0.10]]);
    const hasGrievance = rnd() > 0.4;
    const grievance = hasGrievance
      ? weighted<GrievanceKey>([['water', 0.2], ['power', 0.16], ['roads', 0.13], ['jobs', 0.12], ['health', 0.1], ['farm_debt', 0.1], ['drugs', 0.07], ['education', 0.07], ['other', 0.05]])
      : undefined;
    const spec: VisitSpec = {
      head: members[0].name, workerId: w.id, boothNo,
      addr: `H.No ${20 + Math.floor(rnd() * 260)}, ${pick(['Gali No 3', 'Gali No 5', 'Gali No 8', 'Main Bazaar', 'Ward 4', 'Ward 7', 'Model Colony'])}`,
      outcome: 'met', hoursAgo: hrs, members, spokenTo: 1 + Math.floor(rnd() * Math.min(3, members.length)),
      flagHung: rnd() > 0.6, grievance,
      grievanceNote: grievance ? GRV_NOTE[grievance][Math.floor(rnd() * GRV_NOTE[grievance].length)] : undefined,
      lean, loop: grievance ? weighted<LoopStatus>([['raised', 0.5], ['routed', 0.35], ['resolved', 0.15]]) : undefined,
      extraHousePic: rnd() > 0.7,
    };
    const v = mkVisit(spec);
    // only ~55% of met visits carry photos → keeps total near the mockup's count
    if (rnd() > 0.55) v.photos = [];
    out.push(v);
  }
  return out;
}

const GRV_NOTE: Record<GrievanceKey, string[]> = {
  water: ['No piped supply, tanker comes twice a week', 'Handpump water salty', 'Low pressure, dries by noon'],
  power: ['Frequent cuts in the evening', 'Transformer burnt, not replaced', 'High bills, low voltage'],
  roads: ['Potholes after last monsoon', 'No street lights on the lane', 'Road never tarred'],
  jobs: ['Youth migrating for work', 'Factory shut, no local jobs', 'Wants skill training centre'],
  health: ['Nearest hospital 12km away', 'No doctor at the dispensary', 'Dengue cases this month'],
  farm_debt: ['MSP payment delayed', 'Loan interest piling up', 'Fertiliser shortage at co-op'],
  drugs: ['Youth addiction rising in ward', 'Wants de-addiction camp', 'Peddlers near the chowk'],
  education: ['School lacks teachers', 'No bus for girls to college', 'Broken classrooms'],
  other: ['Stray cattle at night', 'Garbage not collected', 'Ration card pending'],
};

// Table shows a short RECENT sample (≤5 pages). The hero aggregates below are
// separate, at real campaign scale (a week of D2D reaches tens of thousands).
export const VISITS: D2DVisit[] = [...CURATED, ...generated(240)];

// ── campaign-scale aggregates (headline KPIs / donut / issues) ───────────────
// Magnitudes are fixed to a realistic week; PROPORTIONS (outcome mix, issue mix,
// lean split) are derived from the sample so everything stays internally
// consistent. Formatting is manual (deterministic) to avoid locale hydration drift.
export function fmt(n: number): string {
  return Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}
export interface CampaignStats {
  households: number; planned: number; members: number; photos: number;
  grievances: number; followUp: number; supportPct: number;
  leanCounts: Record<D2DLean, number>; leanTotal: number;
  outcomeSplit: { outcome: D2DOutcome; count: number; pct: number }[];
  topIssues: { cat: GrievanceKey; count: number }[];
}
function computeCampaignStats(): CampaignStats {
  const met = VISITS.filter((v) => v.outcome === 'met');
  const total = VISITS.length || 1;
  const outcomeCounts: Record<D2DOutcome, number> = { met: 0, not_home: 0, refused: 0, revisit: 0 };
  VISITS.forEach((v) => { outcomeCounts[v.outcome] += 1; });
  const grv: Record<string, number> = {};
  met.forEach((v) => { const g = v.survey?.grievanceCategory; if (g) grv[g] = (grv[g] || 0) + 1; });
  const leanCounts: Record<D2DLean, number> = { supporter: 0, leaning: 0, undecided: 0, opposed: 0 };
  met.forEach((v) => { if (v.survey?.lean) leanCounts[v.survey.lean] += 1; });
  const leanTotal = leanCounts.supporter + leanCounts.leaning + leanCounts.undecided + leanCounts.opposed;
  const supportPct = leanTotal ? Math.round(((leanCounts.supporter + leanCounts.leaning) / leanTotal) * 100) : 0;

  // fixed weekly magnitudes
  const households = 47_200, planned = 78_000, members = 138_400, photos = 22_600, grievances = 9_480, followUp = 6_840;

  const order: D2DOutcome[] = ['met', 'not_home', 'refused', 'revisit'];
  const outcomeSplit = order.map((o) => {
    const p = outcomeCounts[o] / total;
    return { outcome: o, count: Math.round(households * p), pct: Math.round(p * 100) };
  });
  outcomeSplit[0].count += households - outcomeSplit.reduce((s, x) => s + x.count, 0); // absorb rounding

  const grvSample = Object.values(grv).reduce((a, b) => a + b, 0) || 1;
  const topIssues = Object.entries(grv).sort((a, b) => b[1] - a[1]).slice(0, 5)
    .map(([k, n]) => ({ cat: k as GrievanceKey, count: Math.round(grievances * (n / grvSample)) }));

  return { households, planned, members, photos, grievances, followUp, supportPct, leanCounts, leanTotal, outcomeSplit, topIssues };
}
export const CAMPAIGN_STATS = computeCampaignStats();

// ── campaigns ────────────────────────────────────────────────────────────────
export const CAMPAIGNS: BoothCampaign[] = [
  { id: 'c1', name: 'Har Ghar Jhanda', description: 'Flag & poster drive - every supporter household hangs the campaign flag',
    constituency: 'Amritsar East', district: 'Amritsar', booths: [42, 51, 47], startDate: daysAgo(12), endDate: daysAgo(-4), targetDoors: 400, doorsDone: 268, workerIds: ['w1', 'w2'], status: 'active' },
  { id: 'c2', name: 'Booth Parivar Survey', description: 'Household headcount + voter-ID match + grievance capture, booth by booth',
    constituency: 'Jalandhar West', district: 'Jalandhar', booths: [118, 122], startDate: daysAgo(9), endDate: daysAgo(-6), targetDoors: 300, doorsDone: 182, workerIds: ['w3', 'w7'], status: 'active' },
  { id: 'c3', name: 'Naujawan Voter-ID Drive', description: 'Register first-time & missing young voters (18-25) at the doorstep',
    constituency: 'Ludhiana South', district: 'Ludhiana', booths: [88, 91], startDate: daysAgo(6), endDate: daysAgo(-10), targetDoors: 250, doorsDone: 97, workerIds: ['w4'], status: 'active' },
  { id: 'c5', name: 'Nasha-Mukt Ward Drive', description: 'De-addiction awareness + at-risk household mapping, ward by ward',
    constituency: 'Bathinda Urban', district: 'Bathinda', booths: [63, 67], startDate: daysAgo(8), endDate: daysAgo(-9), targetDoors: 350, doorsDone: 213, workerIds: ['w6', 'w2'], status: 'active' },
  { id: 'c4', name: 'Revisit Undecided - Doaba', description: 'Second-touch on undecided households flagged in first pass',
    constituency: 'Patiala Rural', district: 'Patiala', booths: [12, 19], startDate: daysAgo(20), endDate: daysAgo(3), targetDoors: 150, doorsDone: 150, workerIds: ['w5', 'w6'], status: 'completed' },
];
