// 117 Punjab Vidhan Sabha constituencies — generated from src/data/punjab-ac.json
// (authoritative ECI geometry) by scripts/gen-constituencies.cjs. Read-only.
export type Region = 'Majha' | 'Doaba' | 'Malwa';
export interface Constituency { id: string; name: string; district: string; region: Region; no: number; }
const C = (name: string, district: string, region: Region, no: number): Constituency => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''), name, district, region, no,
});
export const CONSTITUENCIES: Constituency[] = [
  C("Sujanpur", "Gurdaspur", 'Majha', 1),
  C("Bhoa", "Gurdaspur", 'Majha', 2),
  C("Pathankot", "Gurdaspur", 'Majha', 3),
  C("Gurdaspur", "Gurdaspur", 'Majha', 4),
  C("Dina Nagar", "Gurdaspur", 'Majha', 5),
  C("Qadian", "Gurdaspur", 'Majha', 6),
  C("Batala", "Gurdaspur", 'Majha', 7),
  C("Sri Hargobindpur", "Gurdaspur", 'Majha', 8),
  C("Fatehgarh Churian", "Gurdaspur", 'Majha', 9),
  C("Dera Baba Nanak", "Gurdaspur", 'Majha', 10),
  C("Ajnala", "Amritsar", 'Majha', 11),
  C("Raja Sansi", "Amritsar", 'Majha', 12),
  C("Majitha", "Amritsar", 'Majha', 13),
  C("Jandiala", "Amritsar", 'Majha', 14),
  C("Amritsar North", "Amritsar", 'Majha', 15),
  C("Amritsar West", "Amritsar", 'Majha', 16),
  C("Amritsar Central", "Amritsar", 'Majha', 17),
  C("Amritsar East", "Amritsar", 'Majha', 18),
  C("Amritsar South", "Amritsar", 'Majha', 19),
  C("Attari", "Amritsar", 'Majha', 20),
  C("Tarn Taran", "Amritsar", 'Majha', 21),
  C("Khem Karan", "Amritsar", 'Majha', 22),
  C("Patti", "Amritsar", 'Majha', 23),
  C("Khadoor Sahib", "Amritsar", 'Majha', 24),
  C("Baba Bakala", "Amritsar", 'Majha', 25),
  C("Bholath", "Kapurthala", 'Doaba', 26),
  C("Kapurthala", "Kapurthala", 'Doaba', 27),
  C("Sultanpur Lodhi", "Kapurthala", 'Doaba', 28),
  C("Phagwara", "Kapurthala", 'Doaba', 29),
  C("Phillaur", "Jalandhar", 'Doaba', 30),
  C("Nakodar", "Jalandhar", 'Doaba', 31),
  C("Shahkot", "Jalandhar", 'Doaba', 32),
  C("Kartarpur", "Jalandhar", 'Doaba', 33),
  C("Jalandhar West", "Jalandhar", 'Doaba', 34),
  C("Jalandhar Central", "Jalandhar", 'Doaba', 35),
  C("Jalandhar North", "Jalandhar", 'Doaba', 36),
  C("Jalandhar Cantt.", "Jalandhar", 'Doaba', 37),
  C("Adampur", "Jalandhar", 'Doaba', 38),
  C("Mukerian", "Hoshiarpur", 'Doaba', 39),
  C("Dasuya", "Hoshiarpur", 'Doaba', 40),
  C("Urmar", "Hoshiarpur", 'Doaba', 41),
  C("Sham Chaurasi", "Hoshiarpur", 'Doaba', 42),
  C("Hoshiarpur", "Hoshiarpur", 'Doaba', 43),
  C("Chabbewal", "Hoshiarpur", 'Doaba', 44),
  C("Garhshankar", "Hoshiarpur", 'Doaba', 45),
  C("Banga", "Nawanshahr", 'Doaba', 46),
  C("Nawan Shahr", "Nawanshahr", 'Doaba', 47),
  C("Balachaur", "Nawanshahr", 'Doaba', 48),
  C("Anandpur Sahib", "Rupnagar", 'Malwa', 49),
  C("Rupnagar", "Rupnagar", 'Malwa', 50),
  C("Chamkaur Sahib", "Rupnagar", 'Malwa', 51),
  C("Kharar", "Rupnagar", 'Malwa', 52),
  C("S.A.S.Nagar", "Rupnagar", 'Malwa', 53),
  C("Bassi Pathana", "Fatehgarh Sahib", 'Malwa', 54),
  C("Fatehgarh Sahib", "Fatehgarh Sahib", 'Malwa', 55),
  C("Amloh", "Fatehgarh Sahib", 'Malwa', 56),
  C("Khanna", "Ludhiana", 'Malwa', 57),
  C("Samrala", "Ludhiana", 'Malwa', 58),
  C("Sahnewal", "Ludhiana", 'Malwa', 59),
  C("Ludhiana East", "Ludhiana", 'Malwa', 60),
  C("Ludhiana South", "Ludhiana", 'Malwa', 61),
  C("Atam Nagar", "Ludhiana", 'Malwa', 62),
  C("Ludhiana Central", "Ludhiana", 'Malwa', 63),
  C("Ludhiana West", "Ludhiana", 'Malwa', 64),
  C("Ludhiana North", "Ludhiana", 'Malwa', 65),
  C("Gill", "Ludhiana", 'Malwa', 66),
  C("Payal", "Ludhiana", 'Malwa', 67),
  C("Dakha", "Ludhiana", 'Malwa', 68),
  C("Raikot", "Ludhiana", 'Malwa', 69),
  C("Jagraon", "Ludhiana", 'Malwa', 70),
  C("Nihal Singhwala", "Moga", 'Malwa', 71),
  C("Bhagha Purana", "Moga", 'Malwa', 72),
  C("Moga", "Moga", 'Malwa', 73),
  C("Dharamkot", "Moga", 'Malwa', 74),
  C("Zira", "Firozpur", 'Malwa', 75),
  C("Firozpur City", "Firozpur", 'Malwa', 76),
  C("Firozpur Rural", "Firozpur", 'Malwa', 77),
  C("Guru Har Sahai", "Firozpur", 'Malwa', 78),
  C("Jalalabad", "Firozpur", 'Malwa', 79),
  C("Fazilka", "Firozpur", 'Malwa', 80),
  C("Abohar", "Firozpur", 'Malwa', 81),
  C("Balluana", "Firozpur", 'Malwa', 82),
  C("Lambi", "Muktsar", 'Malwa', 83),
  C("Gidderbaha", "Muktsar", 'Malwa', 84),
  C("Malout", "Muktsar", 'Malwa', 85),
  C("Muktsar", "Muktsar", 'Malwa', 86),
  C("Faridkot", "Faridkot", 'Malwa', 87),
  C("Kotkapura", "Faridkot", 'Malwa', 88),
  C("Jaitu", "Faridkot", 'Malwa', 89),
  C("Rampura Phul", "Bathinda", 'Malwa', 90),
  C("Bhucho Mandi", "Bathinda", 'Malwa', 91),
  C("Bathinda Urban", "Bathinda", 'Malwa', 92),
  C("Bathinda Rural", "Bathinda", 'Malwa', 93),
  C("Talwandi Sabo", "Bathinda", 'Malwa', 94),
  C("Maur", "Bathinda", 'Malwa', 95),
  C("Mansa", "Mansa", 'Malwa', 96),
  C("Sardulgarh", "Mansa", 'Malwa', 97),
  C("Budhlada", "Mansa", 'Malwa', 98),
  C("Lehra", "Sangrur", 'Malwa', 99),
  C("Dirba", "Sangrur", 'Malwa', 100),
  C("Sunam", "Sangrur", 'Malwa', 101),
  C("Bhadaur", "Sangrur", 'Malwa', 102),
  C("Barnala", "Sangrur", 'Malwa', 103),
  C("Mehal Kalan", "Sangrur", 'Malwa', 104),
  C("Malerkotla", "Sangrur", 'Malwa', 105),
  C("Amargarh", "Sangrur", 'Malwa', 106),
  C("Dhuri", "Sangrur", 'Malwa', 107),
  C("Sangrur", "Sangrur", 'Malwa', 108),
  C("Nabha", "Patiala", 'Malwa', 109),
  C("Patiala Rural", "Patiala", 'Malwa', 110),
  C("Rajpura", "Patiala", 'Malwa', 111),
  C("Dera Bassi", "Patiala", 'Malwa', 112),
  C("Ghanaur", "Patiala", 'Malwa', 113),
  C("Sanour", "Patiala", 'Malwa', 114),
  C("Patiala", "Patiala", 'Malwa', 115),
  C("Samana", "Patiala", 'Malwa', 116),
  C("Shutrana", "Patiala", 'Malwa', 117),
];
export const DISTRICTS: string[] = Array.from(new Set(CONSTITUENCIES.map((c) => c.district))).sort();
export const CONSTITUENCY_NAMES: string[] = CONSTITUENCIES.map((c) => c.name);
export const TOTAL_SEATS = CONSTITUENCIES.length;
// Normalize for matching GeoJSON feature names to data names (strip (SC)/(ST), punctuation, case).
export const normName = (s: string): string =>
  (s || '').toLowerCase().replace(/\((?:sc|st)\)/g, '').replace(/[^a-z0-9]/g, '');
