/**
 * Notification sound preferences — single source of truth.
 *
 * Used by NotificationCenter (new-lead / update alerts), FounderDashboard
 * (the home-page "ready" cue), and the Settings "Notifications & Sounds"
 * panel. All three read/write the SAME localStorage keys so toggling mute in
 * one place is honoured everywhere (after the next play).
 *
 * Sound files live in public/sounds/ and are (re)generated by
 * scripts/gen_notification_sounds.py — the soft glass-bell family.
 */

export type SoundEvent = 'new' | 'update' | 'ready'

export const SOUND_FILES: Record<SoundEvent, string> = {
  new: '/sounds/new-lead.wav',
  update: '/sounds/update.wav',
  ready: '/sounds/page-load.mp3', // custom file supplied by the team
}

export const SOUND_LABELS: Record<SoundEvent, string> = {
  new: 'New lead',
  update: 'Lead update',
  ready: 'Page ready',
}

// Master mute key kept as-is for back-compat with the existing bell toggle.
const MUTED_KEY = 'wc-notif-muted'
const ENABLED_KEY: Record<SoundEvent, string> = {
  new: 'wc-sound-new',
  update: 'wc-sound-update',
  ready: 'wc-sound-ready',
}

function read(key: string): string | null {
  if (typeof window === 'undefined') return null
  try { return localStorage.getItem(key) } catch { return null }
}
function write(key: string, val: string) {
  if (typeof window === 'undefined') return
  try { localStorage.setItem(key, val) } catch { /* private mode — ignore */ }
}

export function isMuted(): boolean {
  return read(MUTED_KEY) === '1'
}
export function setMuted(v: boolean) {
  write(MUTED_KEY, v ? '1' : '0')
}

// Per-event toggles default ON (including the page-ready cue).
export function isEventEnabled(ev: SoundEvent): boolean {
  return read(ENABLED_KEY[ev]) !== '0'
}
export function setEventEnabled(ev: SoundEvent, v: boolean) {
  write(ENABLED_KEY[ev], v ? '1' : '0')
}

// Lazily-built, reused <audio> elements so we don't re-fetch on every play.
const cache: Partial<Record<SoundEvent, HTMLAudioElement>> = {}

/** Play an event sound, respecting master mute + the per-event toggle. */
export function playSound(ev: SoundEvent) {
  if (typeof window === 'undefined' || typeof Audio === 'undefined') return
  if (isMuted() || !isEventEnabled(ev)) return
  preview(ev)
}

/** Play a sound IGNORING toggles — for the Configure preview buttons. */
export function preview(ev: SoundEvent) {
  if (typeof window === 'undefined' || typeof Audio === 'undefined') return
  let a = cache[ev]
  if (!a) { a = new Audio(SOUND_FILES[ev]); cache[ev] = a }
  try {
    a.currentTime = 0
    void a.play().catch(() => { /* autoplay blocked until first interaction */ })
  } catch { /* ignore */ }
}
