// ─────────────────────────────────────────────────────────────────────────────
// Windchasers CORE COMMUNICATIONS — the checklist of every message the agent
// must handle autonomously, surfaced on Brain → Eval → Communications.
//
// DISPLAY TRUTH ONLY (same philosophy as core/src/configs/journeys.ts):
// send-truth lives in core/src/lib/services/whatsappSender.ts + the intake
// routes (facebook-lead, leads/inbound, cron/webinar-reminder,
// cron/follow-up-sequence). Update status/note here IN THE SAME COMMIT as any
// sender change. Body text mirrors docs/templates.md; where Meta holds the
// only exact copy, the body is a close mirror and the note says so.
// ─────────────────────────────────────────────────────────────────────────────

import type { CoreCommunication } from '@/configs/types';

export const WINDCHASERS_COMMUNICATIONS: CoreCommunication[] = [
  // ── WELCOME — new leads, per source ────────────────────────────────────────
  {
    id: 'fb_pilot_welcome',
    category: 'welcome',
    title: 'FB Lead Ad welcome — pilot',
    trigger: 'Meta lead form / website with pilot signals (pilot/CPL/PPL/CHPL/DGCA/flying) → pickWelcomeTemplate → sendWelcomeTemplate',
    channel: 'whatsapp',
    template: 'windchasers_pilot_welcome_v3',
    body: 'Hi {{customer_name}}, welcome to Windchasers — India\'s leading pilot training academy.\n\nYou\'ve taken the first step toward the cockpit. A counsellor will reach out shortly to map your CPL journey.\n\n- Team Windchasers',
    status: 'live',
    note: 'Meta-approved (named param customer_name). Fires instantly on intake, deduped by phone + cooldown. Auto-falls-back to _v2 only if _v3 review lapses (WELCOME_FALLBACK).',
  },
  {
    id: 'fb_generic_welcome',
    category: 'welcome',
    title: 'FB Lead Ad welcome — generic',
    trigger: 'Meta lead form / website, non-pilot & non-cabin-crew source (home page / generic ads) → pickWelcomeTemplate → sendWelcomeTemplate',
    channel: 'whatsapp',
    template: 'windchasers_generic_welcome_v3',
    body: 'Hi {{customer_name}}, welcome to Windchasers Aviation Academy.\n\nWe have training paths for DGCA Ground Classes, Pilot Training, Cabin Crew and more. A counsellor will reach out shortly.\n\n- Team Windchasers',
    status: 'live',
    note: 'Meta-approved (named param customer_name). Auto-falls-back to _v1 only if _v3 review lapses (WELCOME_FALLBACK). Also the fallback target for cabin-crew if that template is ever unavailable.',
  },
  {
    id: 'fb_cabin_crew_welcome',
    category: 'welcome',
    title: 'FB Lead Ad / website welcome — cabin crew',
    trigger: 'Cabin-crew signals (course_interest cabin_crew, air hostess, flight attendant, /cabin-crew landing) → isCabinCrewSource → sendCabinCrewWelcome',
    channel: 'whatsapp',
    template: 'windchasers_cabin_crew_welcome_v1',
    body: 'Hi {{customer_name}}, thanks for sharing your interest in our Cabin Crew programme.\n\nYou\'re one step closer to a career in the skies. A counsellor will reach out shortly to walk you through training, placements and the next batch.\n\n- Team Windchasers',
    status: 'live',
    note: 'Meta-approved (named param customer_name) — LIVE and sending (dedicated cabin-crew copy). Falls back to windchasers_generic_welcome_v3 only if unavailable. Note: current live cabin-crew leads arrive via Google Ads /cabin-crew (touchpoint form), not Meta.',
  },
  {
    id: 'fb_parent_welcome',
    category: 'welcome',
    title: 'FB Lead Ad welcome — parent enquiry',
    trigger: 'Meta lead form where form/campaign/ad name contains "parent" (isParentSource)',
    channel: 'whatsapp',
    template: 'windchasers_pilot_parents_welcome_v1',
    body: 'Hi {{parent_name}}, welcome to Windchasers.\n\nGiving your child a career in the skies starts here. A counsellor will reach out shortly to walk you through the pilot training journey, costs and timelines.\n\n- Team Windchasers',
    status: 'live',
    note: 'Meta-approved and LIVE (sendParentWelcomeTemplate, NAMED param parent_name — not interchangeable with customer_name).',
    sampleParams: { parent_name: 'Mrs. Sharma' },
  },
  {
    id: 'webform_welcome',
    category: 'welcome',
    title: 'Website form welcome — generic inbound',
    trigger: 'Any website form lead that is not PAT / demo / webinar / FB (POST /api/agent/leads/inbound)',
    channel: 'whatsapp',
    status: 'missing',
    note: 'NO welcome goes out today — the send branch is disabled (inbound route) and the old windchasers_followup template was deleted from Meta. Needs new copy + Meta submission, then re-enable the branch.',
  },
  {
    id: 'webinar_confirm',
    category: 'welcome',
    title: 'Webinar registration confirm',
    trigger: 'Zoom registration → Pabbly → /api/agent/leads/inbound (form_type: webinar) → sendWebinarConfirm',
    channel: 'whatsapp',
    template: 'windchasers_webinar_confirmation_v1',
    body: 'Hi {{customer_name}}, you\'re registered for {{topic}} on {{date}} at {{time}}.\n\nThe join link will come from Zoom — keep an eye on your email. We\'ll also remind you here before we go live.\n\n- Team Windchasers',
    buttons: ['Join WhatsApp Group'],
    status: 'live',
    note: 'Meta-approved and LIVE. NAMED params: customer_name · topic · date · time (dateTime is split on " at "). Single template for ALL audiences.',
    sampleParams: { topic: 'Cabin Crew Career Webinar', date: '18 July 2026', time: '11:30 AM IST' },
  },
  {
    id: 'webinar_confirm_parents',
    category: 'welcome',
    title: 'Webinar confirm — parents page',
    trigger: 'Webinar registration tagged parent (windchasers.in/webinar/parents) → sendWebinarConfirmParents',
    channel: 'whatsapp',
    template: 'windchasers_webinar_confirmation_v1',
    body: 'Hi {{customer_name}}, you\'re registered for {{topic}} on {{date}} at {{time}}.\n\nThe join link will come from Zoom — keep an eye on your email. We\'ll also remind you here before we go live.\n\n- Team Windchasers',
    buttons: ['Join WhatsApp Group'],
    status: 'live',
    note: 'No parent-specific webinar template exists — sendWebinarConfirmParents() aliases the shared windchasers_webinar_confirmation_v1 (param customer_name). Kept as a distinct checklist row for the parents landing page.',
    sampleParams: { topic: 'Cabin Crew Career Webinar', date: '18 July 2026', time: '11:30 AM IST' },
  },

  // ── INBOUND — replies to incoming lead messages (AI, prompt + knowledge) ───
  {
    id: 'whatsapp_ai_reply',
    category: 'inbound',
    title: 'WhatsApp reply — AI counsellor (Avia)',
    trigger: 'Every inbound WhatsApp message → agent engine (Meta webhook), inside the 24h window',
    channel: 'whatsapp',
    body: 'Great question! The DGCA Ground Classes batch starts on the 7th of every month — fees are ₹2.35 lakh (online) / ₹2.75 lakh (classroom), and the full CPL journey typically runs 18–24 months. Want me to book you a counselling call to map your path?',
    status: 'live',
    note: 'Free-form AI reply from brands/windchasers/prompts (Avia persona + brand facts) + knowledge_base search. Body shown is a representative sample, not fixed copy.',
  },
  {
    id: 'webchat_ai_reply',
    category: 'inbound',
    title: 'Website chat reply — AI counsellor (Avia)',
    trigger: 'Visitor types in the website widget → /api/agent/web/chat (streaming)',
    channel: 'webchat',
    body: 'Hi! I\'m Avia, Windchasers\' AI Aviation Counsellor. To become a commercial pilot you\'ll go through DGCA ground classes, flying hours and licensing — I can walk you through fees, timelines and the right batch for you. What stage are you at?',
    status: 'live',
    note: 'Same prompt + knowledge base as WhatsApp; scripted opening bubbles come from the widget config, replies are AI.',
  },

  // ── CONFIRMATION — transactional confirms ──────────────────────────────────
  {
    id: 'pat_result',
    category: 'confirmation',
    title: 'PAT result message',
    trigger: 'Pilot Aptitude Test submitted on the website (source: pat)',
    channel: 'whatsapp',
    template: 'windchasers_pat_result_v2',
    body: 'Hi {{customer_name}}! Your Pilot Aptitude Test result is in.\n\nScore: {{score}}/100\nTier: {{tier}}\n\n{{tier_message}}\n\nA counsellor will be in touch shortly.\n\n- Team Windchasers',
    status: 'live',
    note: 'Code sends _v2 (docs/templates.md still lists v1 — doc drift, doc update pending).',
    sampleParams: { score: '58', tier: 'Strong', tier_message: 'You\'re well-positioned. Worth a 1:1 to map your training path.' },
  },
  {
    id: 'demo_confirm_online',
    category: 'confirmation',
    title: 'Demo confirm — online',
    trigger: 'Online demo booked on the website (demo_type: online); calendar event created first',
    channel: 'whatsapp',
    template: 'windchasers_demo_online_v2',
    body: 'Hi {{customer_name}}, your online demo with Windchasers is confirmed.\n\nDate: {{date}}\nTime: {{time}}\n\nThe Meet link will arrive 30 minutes before the session. Tap "Add to Calendar" below so you don\'t miss it.\n\n- Team Windchasers',
    buttons: ['Add to Calendar'],
    status: 'live',
    sampleParams: { date: 'Mon, Jul 14', time: '12:00 PM IST' },
  },
  {
    id: 'demo_confirm_offline',
    category: 'confirmation',
    title: 'Demo confirm — at the facility',
    trigger: 'Offline/in-facility demo booked on the website (demo_type: offline or unset)',
    channel: 'whatsapp',
    template: 'windchasers_demo_offline_v2',
    body: 'Hi {{customer_name}}, your demo at the Windchasers facility is confirmed.\n\nDate: {{date}}\nTime: {{time}}\n\nAddress details and what to bring will follow shortly. Reply here if you need to reschedule.\n\n- Team Windchasers',
    status: 'live',
    sampleParams: { date: 'Mon, Jul 14', time: '12:00 PM IST' },
  },
  {
    id: 'booking_confirmation',
    category: 'confirmation',
    title: 'Booking confirmation',
    trigger: 'Call/session booked through the agent (booking flow)',
    channel: 'whatsapp',
    template: 'booking_confirmation',
    body: 'Hi {{customer_name}}, your {{title}} is confirmed for {{date_time}}. Tap below to add it to your calendar.',
    buttons: ['Add to Calendar'],
    status: 'missing',
    note: 'BRAND BLEED: shared generic name — NOT registered in the Windchasers WABA (verified via Graph API 2026-07-12), and the bcon-registered copy says "BCON team"/bconclub.com. On Windchasers this send FAILS. Fix: register a windchasers_booking_confirmation_* template + point the sender at it per-brand.',
    sampleParams: { title: 'Counselling Call', date_time: 'Mon, Jul 14 · 4:00 PM' },
  },

  // ── REMINDER ───────────────────────────────────────────────────────────────
  {
    id: 'webinar_reminder',
    category: 'reminder',
    title: 'Webinar reminder — 24h + 2h before',
    trigger: 'Hourly cron (/api/cron/webinar-reminder) in the 20–28h and 1–4h windows before webinar_date',
    channel: 'whatsapp',
    template: 'windchasers_webinar_reminder_v1',
    body: 'Hi {{customer_name}}, reminder — {{webinar_name}} starts {{when}}.\n\nThe Zoom link is in your registration email. See you there!\n\n- Team Windchasers',
    status: 'partial',
    note: 'Cron + idempotency markers live, sender wired (sendWebinarReminder) — but the template is NOT registered in the Windchasers WABA (verified via Graph API 2026-07-12), so reminders fail until it is created + approved at Meta.',
    sampleParams: { when: 'tomorrow at 5:00 PM' },
  },
  {
    id: 'booking_reminder',
    category: 'reminder',
    title: 'Booking reminder — 24h / 1h / 30m',
    trigger: 'Cron (/api/cron/booking-reminders) before a booked call',
    channel: 'whatsapp',
    template: 'booking_reminder',
    body: 'Hi {{customer_name}}, reminder — your {{title}} is {{when}}. Tap below to join.',
    buttons: ['Join Meeting'],
    status: 'missing',
    note: 'BRAND BLEED: shared generic name — NOT registered in the Windchasers WABA (verified 2026-07-12); bcon-registered copy is BCON-branded. Send FAILS on Windchasers. Fix: windchasers_* registration + per-brand sender.',
    sampleParams: { title: 'Counselling Call', when: 'in 1 hour' },
  },

  // ── FOLLOW-UP — re-engagement ──────────────────────────────────────────────
  {
    id: 'rnr_step1',
    category: 'followup',
    title: 'RNR re-engagement — step 1',
    trigger: 'Call rang, no answer (RNR task due) → cron/follow-up-sequence; pilot vs generic by lead source',
    channel: 'whatsapp',
    template: 'rnr_pilot_1_v1',
    body: 'Hi {{customer_name}}, we tried reaching you about your pilot training enquiry but couldn\'t connect. When\'s a good time to call you back?\n\n- Team Windchasers',
    status: 'live',
    note: 'Template picked at send time: rnr_{pilot|generic}_1_v1. Capped 2 per lead, cancelled the moment the customer replies.',
  },
  {
    id: 'rnr_step2',
    category: 'followup',
    title: 'RNR re-engagement — step 2',
    trigger: 'Second attempt after step 1 got no reply',
    channel: 'whatsapp',
    template: 'rnr_pilot_2_v1',
    body: 'Hi {{customer_name}}, we tried again but couldn\'t reach you. If you\'re still exploring pilot training, just reply here and a counsellor will take it from there.\n\n- Team Windchasers',
    status: 'live',
    note: 'Template picked at send time: rnr_{pilot|generic}_2_v1. Last automated touch in the RNR ladder.',
  },
  {
    id: 'missed_call_followup',
    category: 'followup',
    title: 'Missed-call follow-up',
    trigger: 'Call logged as No Answer / Voicemail / Busy → note orchestrator RNR sequence',
    channel: 'whatsapp',
    template: 'missed_call_followup',
    body: 'Hi {{customer_name}}, we just tried calling about your {{title}} ({{when}}). Reply here and we\'ll pick it up on WhatsApp.',
    status: 'missing',
    note: 'BRAND BLEED: shared generic name — NOT registered in the Windchasers WABA (verified 2026-07-12); bcon-registered copy is BCON-branded. Send FAILS on Windchasers. Fix: windchasers_* registration + per-brand sender. (RNR steps above already use windchasers rnr_* templates — prefer those.)',
    sampleParams: { title: 'Counselling Call', when: 'today, 4:00 PM' },
  },
  {
    id: 'day135_sequence',
    category: 'followup',
    title: 'Day 1 / 3 / 5 nurture sequence',
    trigger: 'No reply after first contact — day 1 nudge, day 3 value prop, day 5 last touch',
    channel: 'whatsapp',
    status: 'off',
    note: 'Templates not built (placeholders in docs/templates.md) and features.followUpSequence is OFF. Switch on after copy is written + Meta-approved.',
  },
];
