// Auto-generated by scripts/bump-version.js - do not edit
<<<<<<< HEAD
export const APP_VERSION = '0.0.30'
export const BUILD_TIMESTAMP = '2026-06-17T18:06:35.805Z'
=======
export const APP_VERSION = '0.0.24'
export const BUILD_TIMESTAMP = '2026-06-17T15:30:02.249Z'
>>>>>>> 1304c684 (bcon voice: bridge VoBiz call leg into Vapi agent over SIP)
