#!/usr/bin/env node

/**
 * Version bumper — increments the committed app version by ONE patch, with
 * carry-over at 100 so the number stays short:
 *
 *   0.0.23 → 0.0.24 → … → 0.0.99 → 0.1.0 → … → 0.99.99 → 1.0.0
 *
 * Source of truth is package.json (committed). This is invoked by the
 * .git/hooks/pre-commit hook whenever a commit touches the Windchasers agent,
 * so the version climbs by one on every push automatically — no manual edits.
 *
 * Writes three files in lockstep so runtime, API and build all agree:
 *   - package.json            ("version")
 *   - .build-info             (version + timestamp, read by the build-info API)
 *   - src/lib/generated-version.ts (APP_VERSION constant)
 */

const fs = require('fs')
const path = require('path')

const dir = path.join(__dirname, '..')
const pkgPath = path.join(dir, 'package.json')

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'))
let [major, minor, patch] = (pkg.version || '0.0.0').split('.').map((n) => parseInt(n, 10) || 0)

// One patch up, carry at 100.
patch += 1
if (patch >= 100) { patch = 0; minor += 1 }
if (minor >= 100) { minor = 0; major += 1 }

const version = `${major}.${minor}.${patch}`
const timestamp = new Date().toISOString()

pkg.version = version
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')

fs.writeFileSync(
  path.join(dir, '.build-info'),
  JSON.stringify({ version, timestamp, buildDate: new Date().toLocaleString() }, null, 2) + '\n',
)

fs.writeFileSync(
  path.join(dir, 'src/lib/generated-version.ts'),
  `// Auto-generated by scripts/bump-version.js - do not edit\n` +
    `export const APP_VERSION = '${version}'\n` +
    `export const BUILD_TIMESTAMP = '${timestamp}'\n`,
)

console.log(`📦 Version bumped to ${version}`)
