import type { BrandConfig } from './proxe.config';

export const bconConfig: BrandConfig = {
  name: 'BCON',
  brand: 'bcon',
  apiUrl: '/api/agent/web/chat',
  systemPrompt: {
    path: '@/api/prompts/bcon-prompt',
  },
  styles: {
    themePath: '@/styles/theme.css',
  },
  chatStructure: {
    showQuickButtons: true,
    showFollowUpButtons: true,
    maxFollowUps: 3,
    avatar: {
      type: 'image',
      source: '/bcon-icon.png',
    },
  },
  colors: {
    // Primary Colors - Dark/Electric Purple Palette
    primary: '#8B5CF6',              // Electric purple
    primaryLight: '#E0D4FC',          // Light lavender
    primaryDark: '#0A0A0B',           // Near black
    primaryVibrant: '#A78BFA',        // Vibrant purple

    // Gradient
    gradientStart: '#0A0A0B',
    gradientMid: '#8B5CF6',
    gradientEnd: '#A78BFA',

    // Backgrounds
    darkBg: '#0A0A0B',
    darkCard: 'rgba(139, 92, 246, 0.3)',
    darkSurface: 'rgba(10, 10, 11, 0.4)',
    glassBg: 'rgba(139, 92, 246, 0.05)',
    glassBorder: 'rgba(224, 212, 252, 0.1)',
    glassShadow: 'rgba(139, 92, 246, 0.2)',

    // Text Colors
    textPrimary: '#E0D4FC',
    textSecondary: 'rgba(224, 212, 252, 0.7)',
    textTertiary: 'rgba(224, 212, 252, 0.5)',
    textMuted: 'rgba(224, 212, 252, 0.4)',
    white: '#E0D4FC',

    // Borders
    borderLight: 'rgba(224, 212, 252, 0.08)',
    borderMedium: 'rgba(224, 212, 252, 0.12)',
    borderAccent: 'rgba(139, 92, 246, 0.3)',
    borderGlow: 'rgba(139, 92, 246, 0.4)',
    borderColor: 'rgba(139, 92, 246, 0.2)',

    // Accents
    greenSuccess: '#10B981',
    cyanAccent: '#A78BFA',
    orangeAccent: '#8B5CF6',
    goldAccent: '#A78BFA',

    // Background Variants
    bgPrimary: 'rgba(10, 10, 11, 0.05)',
    bgHeader: 'rgba(10, 10, 11, 0.85)',
    bgMessageArea: 'rgba(139, 92, 246, 0.03)',
    bgHover: 'rgba(139, 92, 246, 0.12)',
    bgActive: 'rgba(139, 92, 246, 0.15)',

    // Chat Bubbles
    bubbleUserBg: 'rgba(139, 92, 246, 0.25)',
    bubbleUserBorder: 'rgba(139, 92, 246, 0.7)',
    bubbleUserShadow: '0 8px 32px rgba(139, 92, 246, 0.25)',
    bubbleAiBg: 'rgba(10, 10, 11, 0.3)',
    bubbleAiBorder: 'rgba(10, 10, 11, 0.7)',
    bubbleAiShadow: '0 8px 32px rgba(10, 10, 11, 0.25)',

    // Buttons
    buttonBg: 'rgba(139, 92, 246, 0.25)',
    buttonHover: 'rgba(139, 92, 246, 0.35)',
    buttonActive: 'rgba(139, 92, 246, 0.45)',
  },
  // Quick Actions: 3 buttons shown when chat opens
  quickButtons: [
    'Explore AI Solutions',
    'Book a Strategy Call',
    'See Our Work'
  ],
  // Explore Buttons: 4 service buttons
  exploreButtons: [
    'AI in Business',
    'Brand Marketing',
    'Business Apps',
    'PROXe Platform'
  ],
  // Follow-up Buttons: Dynamic, generated by Claude
  followUpButtons: [],
  // First Message Buttons: Dynamic, generated by Claude
  firstMessageButtons: [],
};
