import type { BrandConfig } from './proxe.config';

export const bconConfig: BrandConfig = {
  name: 'BCON',
  brand: 'bcon',
  apiUrl: '/api/agent/web/chat',
  systemPrompt: {
    path: '@/api/prompts/bcon-prompt',
  },
  styles: {
    themePath: '@/styles/theme.css',
  },
  chatStructure: {
    showQuickButtons: true,
    showFollowUpButtons: true,
    maxFollowUps: 3,
    avatar: {
      type: 'image',
      source: '/bcon-icon.png',
    },
  },
  colors: {
    // Primary — purple only for interactive elements
    primary: '#8B5CF6',
    primaryLight: '#E0D4FC',
    primaryDark: '#0A0A0B',
    primaryVibrant: '#A78BFA',

    // Gradient
    gradientStart: '#0A0A0B',
    gradientMid: '#8B5CF6',
    gradientEnd: '#A78BFA',

    // Backgrounds — pure blacks/dark grays, no purple tint
    darkBg: '#0A0A0B',
    darkCard: 'rgba(255, 255, 255, 0.04)',
    darkSurface: 'rgba(255, 255, 255, 0.02)',
    glassBg: 'rgba(255, 255, 255, 0.03)',
    glassBorder: 'rgba(255, 255, 255, 0.08)',
    glassShadow: 'rgba(0, 0, 0, 0.3)',

    // Text — pure whites and grays
    textPrimary: '#FAFAFA',
    textSecondary: 'rgba(250, 250, 250, 0.7)',
    textTertiary: 'rgba(250, 250, 250, 0.5)',
    textMuted: 'rgba(250, 250, 250, 0.35)',
    white: '#FAFAFA',

    // Borders — neutral grays
    borderLight: 'rgba(255, 255, 255, 0.06)',
    borderMedium: 'rgba(255, 255, 255, 0.10)',
    borderAccent: 'rgba(255, 255, 255, 0.12)',
    borderGlow: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.08)',

    // Accents — semantic only
    greenSuccess: '#10B981',
    cyanAccent: '#06B6D4',
    orangeAccent: '#F59E0B',
    goldAccent: '#EAB308',

    // Background Variants
    bgPrimary: 'rgba(255, 255, 255, 0.02)',
    bgHeader: 'rgba(10, 10, 11, 0.9)',
    bgMessageArea: 'rgba(255, 255, 255, 0.01)',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    bgActive: 'rgba(255, 255, 255, 0.08)',

    // Chat Bubbles — purple only for user bubbles
    bubbleUserBg: 'rgba(139, 92, 246, 0.20)',
    bubbleUserBorder: 'rgba(139, 92, 246, 0.5)',
    bubbleUserShadow: '0 4px 16px rgba(0, 0, 0, 0.3)',
    bubbleAiBg: 'rgba(255, 255, 255, 0.05)',
    bubbleAiBorder: 'rgba(255, 255, 255, 0.08)',
    bubbleAiShadow: '0 4px 16px rgba(0, 0, 0, 0.2)',

    // Buttons — purple for primary action only
    buttonBg: 'rgba(139, 92, 246, 0.20)',
    buttonHover: 'rgba(139, 92, 246, 0.30)',
    buttonActive: 'rgba(139, 92, 246, 0.40)',
  },
  // Quick Actions: 3 buttons shown when chat opens
  quickButtons: [
    'Explore AI Solutions',
    'Book a Strategy Call',
    'See Our Work'
  ],
  // Explore Buttons: 4 service buttons
  exploreButtons: [
    'AI in Business',
    'Brand Marketing',
    'Business Apps',
    'PROXe Platform'
  ],
  // Follow-up Buttons: Dynamic, generated by Claude
  followUpButtons: [],
  // First Message Buttons: Dynamic, generated by Claude
  firstMessageButtons: [],
};
