import type { BrandConfig } from '@/configs';

export const windchasersConfig: BrandConfig = {
  name: 'Windchasers',
  brand: 'windchasers',
  apiUrl: '/api/agent/web/chat',
  systemPrompt: {
    path: '@/api/prompts/windchasers-prompt',
  },
  styles: {
    themePath: '@/styles/theme.css',
  },
  chatStructure: {
    showQuickButtons: true,
    showFollowUpButtons: true,
    maxFollowUps: 3,
    avatar: {
      type: 'image',
      source: '/logo.png',
    },
  },
  colors: {
    // Aligned to docs/DESIGN_SYSTEM.md — Legacy gold #C5A572 / dark #1A1A1A
    // + Stitch on-surface tokens for text and outline-variant for borders
    primary: '#C5A572',              // Legacy gold
    primaryLight: '#e5e2e1',          // Stitch on-surface
    primaryDark: '#1A1A1A',           // Legacy dark
    primaryVibrant: '#C5A572',        // Same as primary (no separate vibrant in legacy)

    // Gradient
    gradientStart: '#1A1A1A',
    gradientMid: '#C5A572',
    gradientEnd: '#C5A572',

    // Backgrounds
    darkBg: '#1A1A1A',
    darkCard: '#1E1E1E',              // Legacy soft black (section bg)
    darkSurface: '#0D0D0D',           // Legacy accent-dark
    glassBg: 'rgba(197, 165, 114, 0.05)',
    glassBorder: 'rgba(77, 70, 59, 0.5)',  // Stitch outline-variant
    glassShadow: 'rgba(197, 165, 114, 0.2)',

    // Text — Stitch on-surface family
    textPrimary: '#e5e2e1',
    textSecondary: '#d1c5b6',
    textTertiary: 'rgba(209, 197, 182, 0.7)',
    textMuted: 'rgba(209, 197, 182, 0.5)',
    white: '#e5e2e1',

    // Borders — Stitch outline-variant + gold accents
    borderLight: 'rgba(77, 70, 59, 0.3)',
    borderMedium: 'rgba(77, 70, 59, 0.5)',
    borderAccent: 'rgba(197, 165, 114, 0.3)',
    borderGlow: 'rgba(197, 165, 114, 0.4)',
    borderColor: 'rgba(197, 165, 114, 0.2)',

    // Accents
    greenSuccess: '#10B981',
    cyanAccent: '#C5A572',
    orangeAccent: '#C5A572',
    goldAccent: '#C5A572',

    // Background Variants
    bgPrimary: 'rgba(26, 26, 26, 0.05)',
    bgHeader: 'rgba(13, 13, 13, 0.85)',     // Legacy accent-dark
    bgMessageArea: 'rgba(197, 165, 114, 0.03)',
    bgHover: 'rgba(197, 165, 114, 0.12)',
    bgActive: 'rgba(197, 165, 114, 0.15)',

    // Chat Bubbles — gold tint user, soft-black AI
    bubbleUserBg: 'rgba(197, 165, 114, 0.25)',
    bubbleUserBorder: 'rgba(197, 165, 114, 0.7)',
    bubbleUserShadow: '0 8px 32px rgba(197, 165, 114, 0.25)',
    bubbleAiBg: '#1E1E1E',
    bubbleAiBorder: 'rgba(77, 70, 59, 0.5)',
    bubbleAiShadow: '0 8px 32px rgba(0, 0, 0, 0.25)',

    // Buttons
    buttonBg: 'rgba(197, 165, 114, 0.15)',
    buttonHover: 'rgba(197, 165, 114, 0.25)',
    buttonActive: 'rgba(197, 165, 114, 0.35)',
  },
  // Quick Actions: audience split + program explorer
  quickButtons: [
    'I want to become a pilot',
    'I am a parent',
    'Explore Training Options'
  ],
  // Explore Buttons: 4 program tiles shown when "Explore Training Options" is clicked
  exploreButtons: [
    'Pilot Training',
    'Flight Schools',
    'Helicopter Pilot',
    'Cabin Crew'
  ],
  // Follow-up Buttons: fallback whitelist when Claude generates contextual buttons.
  // Includes parent-flow exits so post-capture / free-form parent turns can
  // surface them via the LLM follow-up generator if the deterministic flow
  // override hasn't pinned them.
  followUpButtons: [
    'Book a Consultation',
    'Take Pilot Assessment',
    'Talk to a counsellor',
    'Ask another question',
    'Not right now',
    'Ask a Question',
  ],
  // First Message Buttons: Dynamic, generated by Claude (2 buttons after first user message)
  firstMessageButtons: [], // Dynamic, generated by Claude
};
